package export

import (
	"fmt"
	"strings"

	"github.com/kyanite/prism/internal/palette"
)

// ExportCSS exports palette as CSS custom properties
func ExportCSS(p palette.Palette) string {
	// Format: CSS variables with both hex and RGB values

	var sb strings.Builder

	fmt.Fprintf(&sb, "/* Generated by prism.sh - %s */\n", p.Name)
	fmt.Fprintf(&sb, "/* Created: %s */\n", p.CreatedAt.Format("2006-01-02T15:04:05Z07:00"))
	fmt.Fprintf(&sb, "/* Harmony: %s */\n", p.HarmonyRule)
	if isAccessibilityTagged(p.Tags) {
		sb.WriteString("/* Accessible palette: verify each foreground/background pairing before production use. */\n")
	}
	sb.WriteString("\n")

	sb.WriteString(":root {\n")
	sb.WriteString("  /* Hex values */\n")

	for i, c := range p.Colors {
		role := getRoleName(i)
		fmt.Fprintf(&sb, "  --color-%s: %s;\n", role, c.Hex)
	}

	sb.WriteString("\n  /* RGB values (for alpha channel) */\n")
	for i, c := range p.Colors {
		role := getRoleName(i)
		fmt.Fprintf(&sb, "  --color-%s-rgb: %d, %d, %d;\n", role, c.RGB.R, c.RGB.G, c.RGB.B)
	}

	sb.WriteString("}\n")

	return sb.String()
}

func isAccessibilityTagged(tags []string) bool {
	for _, tag := range tags {
		normalized := strings.ToLower(strings.TrimSpace(tag))
		if normalized == "accessible" || strings.HasPrefix(normalized, "wcag") {
			return true
		}
	}
	return false
}

// getRoleName returns semantic role name for color index
func getRoleName(index int) string {
	roles := []string{"primary", "secondary", "accent", "background", "text", "success", "warning"}
	if index < len(roles) {
		return roles[index]
	}
	return fmt.Sprintf("color-%d", index+1)
}
