package export

import (
	"fmt"
	"strings"

	"github.com/kyanite/prism/internal/palette"
)

// ExportTOML exports palette to TOML format
func ExportTOML(p palette.Palette) string {

	var sb strings.Builder

	fmt.Fprintf(&sb, "# Generated by prism.sh - %s\n", p.Name)
	fmt.Fprintf(&sb, "name = \"%s\"\n", p.Name)
	fmt.Fprintf(&sb, "harmony_rule = \"%s\"\n", p.HarmonyRule)
	fmt.Fprintf(&sb, "created_at = \"%s\"\n\n", p.CreatedAt.Format("2006-01-02T15:04:05Z07:00"))

	for i, c := range p.Colors {
		sb.WriteString("[[colors]]\n")
		if c.Name != "" {
			fmt.Fprintf(&sb, "name = \"%s\"\n", c.Name)
		} else {
			fmt.Fprintf(&sb, "name = \"Color %d\"\n", i+1)
		}
		fmt.Fprintf(&sb, "hex = \"%s\"\n", c.Hex)
		fmt.Fprintf(&sb, "role = \"%s\"\n\n", getRoleName(i))
	}

	return sb.String()
}
