#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting
npm run lint

# Run tests
npm run test

# Check if tests passed
if [ $? -ne 0 ]; then
  echo "Tests failed. Please fix them before committing."
  exit 1
fi

echo "Pre-commit checks passed!"
